### ISSUE TITLE
Does not work fine with <NuxtLink />

### ISSUE THREAD

**Issue by Jannchie** [CatsJuice/ipad-cursor#22]
- When using <NuxtLink /> to jump internally, the cursor cannot be moved.
- This may seem unrelated to `updateCursor`. But I've implemented the use of a `MutationObserver` to listen for DOM changes and perform an `updateCursor`. the cursor is subtly unresponsive for a few seconds before being moved normally.

**Comment by Jannchie** [comment]
I've found that this problem only occurs when using `data-cursor="block"` on <NuxtLink />.

**Comment by CatsJuice** [comment]
Thanks for reporting this issue! I did reproduce this problem locally. It happens when the block is active and route navigated.

**Comment by CatsJuice** [comment]
And it recovered because the mouse move into another block again.

**Comment by CatsJuice** [comment]
It's should be solved in release [v0.4.4](https://github.com/CatsJuice/ipad-cursor/releases/tag/v0.4.4).

The reason for this problem is that the inactive elements detected during the scanning of the target element are simply removed from the registered listener, without executing the de-activation handler function. So I execute that function manually before it removed.

Feel free to reopen this issue if the problems persists. Thanks for reporting this issue again!!!
